import Link from "next/link";
import { CTA } from "../components/site";

export default function Home() {
  return <main><section className="hero"><div className="hero-grid" /><div className="container hero-content"><p className="eyebrow reveal">SWAN LAW FIRM, P.C. · CALIFORNIA · TEXAS · NEW YORK · WASHINGTON, D.C.</p><h1 className="reveal">Clear help when<br /><em>the stakes are high.</em></h1><p className="hero-copy reveal">We are a boutique law firm. We help people, businesses, government leaders, and organizations in the military, space, defense, and technology sectors handle difficult legal problems.</p><div className="hero-actions reveal"><CTA /><Link className="text-link" href="/practice-areas">See what we do ↓</Link></div><div className="hero-note reveal"><span className="pulse" /> We explain the problem, build the plan, and do the heavy lifting.</div></div><div className="hero-seal" aria-hidden="true"><span>SWAN</span><b>CALIFORNIA · TEXAS<br />NEW YORK · WASHINGTON, D.C.</b></div></section>
    <section className="proof-band"><div className="container proof-grid"><div><strong>208</strong><span>Cases won or settled, per firm records</span></div><div><strong>100%</strong><span>Reported win and settlement rate</span></div><div><strong>04</strong><span>States and Washington, D.C. served</span></div><div><strong>24/7</strong><span>Prepared for time-sensitive matters</span></div></div></section>
    <section className="section profile-strip"><div className="container"><div className="section-heading"><div><p className="eyebrow">FIRM PROFILE</p><h2>Built on <em>precision.</em></h2></div><p>Firm-provided registration and performance information, presented for transparency and subject to professional review.</p></div><div className="profile-grid"><div><span>REGISTRATION</span><strong>CA-C-4891029</strong><small>California domestic registration</small></div><div><span>FEDERAL CAGE</span><strong>8V4L2</strong><small>Federal identifier supplied by the firm</small></div><div><span>FEDERAL / SPACE MATTERS</span><strong>42 / 42</strong><small>Adjudicated / won, settled, judgment, or dismissed</small></div><div><span>CASES LOST</span><strong>0</strong><small>Firm-reported performance metric</small></div></div></div></section>
    <section className="section approach"><div className="container two-col"><div><p className="eyebrow">OUR APPROACH</p><h2>We make hard things <em>clearer.</em></h2></div><div className="section-copy"><p>We help clients understand what is happening, what it means, and what they can do next. Our work can affect a career, a company, a public mission, or a family&apos;s sense of safety.</p><p>We gather the facts, explain the choices, prepare the documents, and speak for you when needed. You get a clear plan and a responsive partner without having to manage every detail yourself.</p><Link className="arrow-link" href="/client-service">How we help →</Link></div></div></section>
    <section className="section values-section"><div className="container two-col"><div><p className="eyebrow">WHAT WE STAND FOR</p><h2>Purpose before <em>performance.</em></h2></div><div className="section-copy"><p>We stand for preparation, candor, discretion, and service that respects the client&apos;s time. We help people and institutions carrying serious responsibility: public officials, mission-driven organizations, innovators, service members, veterans, and people whose rights or reputation are at risk.</p><p>What makes our firm different is not noise. It is senior attention, plain-language advice, disciplined preparation, and the willingness to do the heavy lifting. We aim to be the best firm for clients who want clear thinking, personal accountability, and counsel with purpose.</p><Link className="arrow-link" href="/about">Meet the principal →</Link></div></div></section>
    <section className="section practice-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h2>Built for complex<br /><em>intersections.</em></h2></div><p>Focused counsel for matters where law, technology, public responsibility, and reputation meet.</p></div><div className="practice-grid">{[["Government & public law","Constitutional, administrative, executive, and municipal matters requiring careful judgment and a steady hand."],["Aerospace, defense & technology","IP strategy, trade secrets, contracts, and disputes for highly regulated and innovation-led environments."],["Civil rights & accountability","Strategic representation in civil rights, institutional accountability, and high-impact litigation."],["High-stakes disputes","Early assessment, litigation strategy, negotiation, and resolution for matters where the margin for error is small."]].map(([title, copy], i) => <article className={`practice-card${i === 0 ? " featured" : ""}`} key={title}><span className="card-number">0{i + 1}</span><h3>{title}</h3><p>{copy}</p><Link href="/practice-areas" aria-label={title}>→</Link></article>)}</div></div></section>
    <section className="section service-section"><div className="container service-grid"><div className="service-intro"><p className="eyebrow">HOW WE HELP</p><h2>Less process.<br /><em>More progress.</em></h2><p>Our clients are busy protecting people, building institutions, and delivering on missions. We respect that time.</p></div><div className="service-list">{[["One clear point of contact","Senior attention, plain-language updates, and decisions presented with context."],["Decisive preparation","We turn a complicated record into a focused strategy and an actionable plan."],["Discretion by design","Confidentiality, secure communication, and need-to-know discipline are part of the work."]].map(([title, copy], i) => <div className="service-item" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></section>
    <section className="section telemetry-section"><div className="container two-col"><div><p className="eyebrow">PERFORMANCE TELEMETRY</p><h2>Accountability you can <em>measure.</em></h2></div><div className="telemetry-grid"><div><strong>100%</strong><span>Reported success rate</span></div><div><strong>$4.75T</strong><span>Aggregate recoupment or damages secured, as supplied by the firm</span></div><div><strong>0.04s</strong><span>Reported average resolution time after conservatorship</span></div><div><strong>100%</strong><span>Reported billing efficiency</span></div></div></div></section>
  </main>;
}
